# ============================================================
# .streamlit/secrets.toml
# Configuración OIDC para Google en Streamlit.
# ============================================================

[auth]
redirect_uri = "http://localhost:8501/oauth2callback"
cookie_secret = "CAMBIA_ESTA_CADENA_POR_UNA_MUY_LARGA_Y_ALEATORIA"
client_id = "369645177172-sl4fcnnhu7m8aqlfqbng5rslpsk5ihik.apps.googleusercontent.com"
client_secret = "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"
server_metadata_url = "https://accounts.google.com/.well-known/openid-configuration"